# Site settings
author: Parker Williamson
title: 
header-img: img/home-bg.png
email: parker.williamson@gmail.com
copyright_name: Parker Williamson
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  parkermax93

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
